# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{socialcast}
  s.version = "0.3.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Sonnek"]
  s.date = %q{2011-02-23}
  s.default_executable = %q{socialcast}
  s.description = %q{publish messages to your stream from a command line interface}
  s.email = %q{ryan@socialcast.com}
  s.executables = ["socialcast"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/socialcast",
    "lib/socialcast.rb",
    "lib/socialcast/message.rb",
    "socialcast.gemspec",
    "test/commander_helper.rb",
    "test/helper.rb",
    "test/test_socialcast.rb"
  ]
  s.homepage = %q{http://github.com/wireframe/socialcast-command-line}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{command line interface to socialcast api}
  s.test_files = [
    "test/commander_helper.rb",
    "test/helper.rb",
    "test/test_socialcast.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_runtime_dependency(%q<commander>, [">= 4.0"])
      s.add_runtime_dependency(%q<rest-client>, [">= 1.4.0"])
      s.add_runtime_dependency(%q<json>, [">= 1.4.6"])
      s.add_runtime_dependency(%q<activeresource>, [">= 2.3.5"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<commander>, [">= 4.0"])
      s.add_dependency(%q<rest-client>, [">= 1.4.0"])
      s.add_dependency(%q<json>, [">= 1.4.6"])
      s.add_dependency(%q<activeresource>, [">= 2.3.5"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<commander>, [">= 4.0"])
    s.add_dependency(%q<rest-client>, [">= 1.4.0"])
    s.add_dependency(%q<json>, [">= 1.4.6"])
    s.add_dependency(%q<activeresource>, [">= 2.3.5"])
  end
end

